name: todolist
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  flutter_blue_plus: ^1.31.15
  awesome_notifications: ^0.10.1
  cupertino_icons: ^1.0.8
  isar: ^3.1.0+1
  build_runner: ^2.4.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1 # ğŸ‘ˆ AquÃ­ estÃ¡ correctamente

flutter:
  uses-material-design: true

  assets:
    - assets/icon/logo.png

# ğŸ‘‡ğŸ¼ Ahora separado, NO adentro de flutter
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/logo.png"
